language: python
python:
- 2.6
- 2.7
install:
- pip install coveralls
script:
- python run_testsuite.py
after_success:
- coveralls
deploy:
  provider: pypi
  user: mottosso
  distributions: "sdist"
  password:
    secure: vW27Vpm6I/yRU0x15lh4TnRfpKeDjQ/ZoFyXvo97zmcR++BIYiyGI1rgzKg4wNLqm3485D6Q9kEr12l7/V4w6YF6j5P8lLq/8mds3B6SIE0eXIOPF16qbKZd52Oa6l3T2rQRXdUBhEK19Smh/EjNrqw3RpOu0BpmECswB/Cyia0Y0/SUK17duBNDHJPmR7L91whZj03hiuHbrpHWXRBlx5J/XUgmVgamHg/7OLqJx9AvTRFxGVxLFTlevX7MctpkzUiu4jU4RDBomnNhDvOJ6HW3SSg3EIHVH9oEc8Rg1qg+bXXDHYno06NNLBl6PO6rB/Lz8zoCB+ZA37idvFj6cVjY71Evk/0vPmccb/QIhYlrbl5Q4pQQFOFBbv2/GqRbEgQ+7ZvCsgl9rhi2HR0RnG1GgrCkHk907EvE0BMryThUcqGu8OI9SKV+uK/itia73Yc3ApuGHbSGLjLylaMvoah8obKpbLVYM8lqPhG0NDnX+9AZqFSDZZmViG0984L7f83Dmo5DxI/ktdYMhRNVG6ePZJ23oXrPeVmf/vZqijGZBkwz6FhnYTejmdgczZXtkvrH6/rHdqMbpRiEK2/npgVH7LH1PTKRPm5KjmipFEn/mjpPcd79u1RGw8yT+CWGKG3lRwY8Gzmlg71DAOAhKATJrZIUnr9hMZxY6aDm2lI=
  on:
    tags: true
    all_branches: true
    python: 2.6